// ============================================================
// 📁 src/rules/constants/ruleCodes.js
// ============================================================

export const RULE_CODES = {
  // Account Delete
  ACTIVE_DEAL_EXISTS: 'ACTIVE_DEAL_EXISTS',
  BALANCE_EXISTS: 'BALANCE_EXISTS',
  PENDING_WITHDRAWALS_EXIST: 'PENDING_WITHDRAWALS_EXIST',
  PENDING_DEPOSITS_EXIST: 'PENDING_DEPOSITS_EXIST',
  PENDING_DISPUTE_EXISTS: 'PENDING_DISPUTE_EXISTS',
  PENDING_REFUND_EXISTS: 'PENDING_REFUND_EXISTS',
  UNDER_INVESTIGATION: 'UNDER_INVESTIGATION',
  ADMIN_ACCOUNT_PROTECTED: 'ADMIN_ACCOUNT_PROTECTED',

  // Identity Change
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  MAX_IDENTITY_CHANGES_REACHED: 'MAX_IDENTITY_CHANGES_REACHED',
  IDENTITY_CHANGE_COOLDOWN: 'IDENTITY_CHANGE_COOLDOWN',
  FRAUD_ALERT_ACTIVE: 'FRAUD_ALERT_ACTIVE',

  // Verification Remove
  INSUFFICIENT_COMPLETED_DEALS: 'INSUFFICIENT_COMPLETED_DEALS',
  LOW_TRUST_SCORE: 'LOW_TRUST_SCORE',
  DISPUTE_HISTORY_EXISTS: 'DISPUTE_HISTORY_EXISTS',

  // Edit Important Fields
  IDENTITY_LOCKED: 'IDENTITY_LOCKED',
  VERIFICATION_REQUIRED: 'VERIFICATION_REQUIRED',
  STRICT_POLICY_RESTRICTION: 'STRICT_POLICY_RESTRICTION',
  FIELD_NOT_ALLOWED: 'FIELD_NOT_ALLOWED',

  // Email/Phone Change
  EMAIL_CHANGE_COOLDOWN: 'EMAIL_CHANGE_COOLDOWN',
  PHONE_CHANGE_COOLDOWN: 'PHONE_CHANGE_COOLDOWN',
  OTP_VERIFICATION_REQUIRED: 'OTP_VERIFICATION_REQUIRED',
  PIN_VERIFICATION_REQUIRED: 'PIN_VERIFICATION_REQUIRED',

  // Merge Accounts
  INVALID_ACCOUNTS: 'INVALID_ACCOUNTS',
  SOURCE_ACCOUNT_HAS_ACTIVE_DEALS: 'SOURCE_ACCOUNT_HAS_ACTIVE_DEALS',
  TARGET_ACCOUNT_HAS_ACTIVE_DEALS: 'TARGET_ACCOUNT_HAS_ACTIVE_DEALS',
  NID_MISMATCH: 'NID_MISMATCH',
  PHONE_MISMATCH: 'PHONE_MISMATCH',
  FACE_VERIFICATION_REQUIRED: 'FACE_VERIFICATION_REQUIRED',

  // Close/Deactivate
  PENDING_TRANSACTIONS_EXIST: 'PENDING_TRANSACTIONS_EXIST',
  PENDING_DISPUTE_OR_REFUND: 'PENDING_DISPUTE_OR_REFUND',
  PENDING_WITHDRAWAL_OR_ESCROW: 'PENDING_WITHDRAWAL_OR_ESCROW',

  // General
  ALLOWED: 'ALLOWED',
  DEAL_NOT_FOUND: 'DEAL_NOT_FOUND',
  DEAL_NOT_ACTIVE: 'DEAL_NOT_ACTIVE',
  DEAL_TERMINAL_STATE: 'DEAL_TERMINAL_STATE',
  NEEDS_ADMIN_APPROVAL: 'NEEDS_ADMIN_APPROVAL',
  NEEDS_MUTUAL_AGREEMENT: 'NEEDS_MUTUAL_AGREEMENT',
  MAX_EXTENSIONS_REACHED: 'MAX_EXTENSIONS_REACHED',
  EXTENSION_TOO_LONG: 'EXTENSION_TOO_LONG',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOT_PARTICIPANT: 'NOT_PARTICIPANT',
  INVALID_REASON: 'INVALID_REASON',

  // ── Chat Rules (chatRules.js আনকমেন্ট করার জন্য প্রয়োজন) ──
  CANNOT_BLOCK_SELF: 'CANNOT_BLOCK_SELF',
  ACTIVE_DEAL_WITH_TARGET: 'ACTIVE_DEAL_WITH_TARGET',
  BLOCK_LIMIT_REACHED: 'BLOCK_LIMIT_REACHED',
  ACTIVE_DEAL_IN_CHAT: 'ACTIVE_DEAL_IN_CHAT',
  GROUP_CHAT_PROTECTED: 'GROUP_CHAT_PROTECTED',
  CANNOT_CHAT_SELF: 'CANNOT_CHAT_SELF',
  USER_BLOCKED: 'USER_BLOCKED',
  SENDER_BLOCKED: 'SENDER_BLOCKED',
  CONVERSATION_MUTED: 'CONVERSATION_MUTED',
  MESSAGE_TOO_SHORT: 'MESSAGE_TOO_SHORT',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  ACTIVE_DEAL_REQUIRED_FOR_OFFER: 'ACTIVE_DEAL_REQUIRED_FOR_OFFER',
  INVALID_MUTE_DURATION: 'INVALID_MUTE_DURATION',
  CANNOT_REPORT_SELF: 'CANNOT_REPORT_SELF',
  REASON_TOO_LONG: 'REASON_TOO_LONG',
  REPORT_LIMIT_REACHED: 'REPORT_LIMIT_REACHED',
  DUPLICATE_REPORT: 'DUPLICATE_REPORT',
};

export default RULE_CODES;
