// src/UI/Notification/NotificationEvents.js

/**
 * 🎯 Unified Notification Events
 * 
 * Single source of truth for all notification events across the app.
 * Every event is defined here once, and used everywhere.
 * 
 * Usage:
 *   notify(NOTIFICATION_EVENTS.CHAT_MESSAGE, { ... })
 *   notify(NOTIFICATION_EVENTS.DEAL_CREATED, { ... })
 * 
 * Benefits:
 *   - Single source of truth
 *   - Easy to maintain
 *   - Auto-completion support
 *   - No typos
 *   - Centralized control
 *
 * ⚠️ IMPORTANT: Adding a key here is NOT enough to make notify() work.
 * You must ALSO add a matching entry in NotificationTemplates.js —
 * NotificationProvider.notify() looks up NotificationTemplates[event]
 * and silently no-ops (no sound, no Firestore write, nothing) if the
 * template is missing.
 *
 * ✅ NEW (this update) — added for the Deal Manager offer-expiry /
 * milestone-submission-review flow in DealManager.jsx:
 *   OFFER_EXPIRED, MILESTONE_SUBMITTED, MILESTONE_REJECTED,
 *   MILESTONE_REFUNDED
 * Remember to add matching templates for these four in
 * NotificationTemplates.js too, or notify() will silently no-op for them.
 */

// ============================================================
// 🎯 Notification Events
// ============================================================
export const NOTIFICATION_EVENTS = {
  // ── 💬 Chat Events ──
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  CHAT_IMAGE: 'CHAT_IMAGE',
  CHAT_PROPOSAL: 'CHAT_PROPOSAL',
  CHAT_PROPOSAL_ACCEPTED: 'CHAT_PROPOSAL_ACCEPTED',
  CHAT_PROPOSAL_REJECTED: 'CHAT_PROPOSAL_REJECTED',
  CHAT_DEAL_STARTED: 'CHAT_DEAL_STARTED',
  CHAT_USER_BLOCKED: 'CHAT_USER_BLOCKED',
  CHAT_USER_UNBLOCKED: 'CHAT_USER_UNBLOCKED',

  // ── 🤝 Deal Events ──
  DEAL_CREATED: 'DEAL_CREATED',
  DEAL_CONFIRMED: 'DEAL_CONFIRMED',
  DEAL_APPROVED: 'DEAL_APPROVED',
  DEAL_REJECTED: 'DEAL_REJECTED',
  DEAL_REOPENED: 'DEAL_REOPENED',
  DEAL_COMPLETED: 'DEAL_COMPLETED',
  DEAL_CANCELLED: 'DEAL_CANCELLED',
  DEAL_EXTENDED: 'DEAL_EXTENDED',
  DEAL_DEADLINE_PASSED: 'DEAL_DEADLINE_PASSED',
  DEADLINE_PASSED: 'DEADLINE_PASSED',
  DEAL_OVERDUE: 'DEAL_OVERDUE',           // Deadline + Grace Period পার হলে
  DISPUTE_OPENED: 'DISPUTE_OPENED',       // কোনো পক্ষ Dispute ওপেন করলে
  OFFER_EXPIRED: 'OFFER_EXPIRED',         // ✅ নতুন — পেন্ডিং অফার ৪৮ ঘণ্টায় সাড়া না পেলে অটো-বাতিল

  // ── 📝 Milestone Events ──
  MILESTONE_FUNDED: 'MILESTONE_FUNDED',
  MILESTONE_REVIEW: 'MILESTONE_REVIEW',
  MILESTONE_RELEASED: 'MILESTONE_RELEASED',
  MILESTONE_SUBMITTED: 'MILESTONE_SUBMITTED',   // ✅ নতুন — সেলার প্রুফসহ কাজ জমা দিলে
  MILESTONE_REJECTED: 'MILESTONE_REJECTED',     // ✅ নতুন — বায়ার জমা দেওয়া কাজ প্রত্যাখ্যান করলে
  MILESTONE_REFUNDED: 'MILESTONE_REFUNDED',     // ✅ নতুন — সময়মতো জমা না দেওয়ায় অটো-রিফান্ড হলে

  // ── ⚠️ Cancellation Events ──
  CANCELLATION_REQUEST: 'CANCELLATION_REQUEST',
  CANCELLATION_APPROVED: 'CANCELLATION_APPROVED',
  CANCELLATION_REJECTED: 'CANCELLATION_REJECTED',

  // ── 💰 Wallet Events ──
  DEPOSIT_APPROVED: 'DEPOSIT_APPROVED',
  DEPOSIT_REJECTED: 'DEPOSIT_REJECTED',
  WITHDRAW_APPROVED: 'WITHDRAW_APPROVED',
  WITHDRAW_REJECTED: 'WITHDRAW_REJECTED',
  WALLET_CREDITED: 'WALLET_CREDITED',
  WALLET_DEBITED: 'WALLET_DEBITED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_RELEASED: 'PAYMENT_RELEASED',

  // ── 👑 Admin Events ──
  ADMIN_ANNOUNCEMENT: 'ADMIN_ANNOUNCEMENT',
  ADMIN_NOTIFICATION: 'ADMIN_NOTIFICATION',

  // ── 👤 User Verification Events (Admin) ──
  USER_VERIFIED: 'USER_VERIFIED',
  USER_BLOCKED: 'USER_BLOCKED',
  USER_UNBLOCKED: 'USER_UNBLOCKED',

  // ── 📋 Report Events (Admin) ──
  REPORT_RESOLVED: 'REPORT_RESOLVED',
  REPORT_CANCELLED: 'REPORT_CANCELLED',

  // ── ⭐ Review Events ──
  REVIEW_RECEIVED: 'REVIEW_RECEIVED',
  REVIEW_REQUESTED: 'REVIEW_REQUESTED',

  // ── ✅ Verification Events ──
  VERIFY_APPROVED: 'VERIFY_APPROVED',
  VERIFY_REJECTED: 'VERIFY_REJECTED',

  // ── 📝 Post Events ──
  POST_APPROVED: 'POST_APPROVED',
  POST_REJECTED: 'POST_REJECTED',

  // ── 📢 System Events ──
  SYSTEM: 'SYSTEM',
  SYSTEM_UPDATE: 'SYSTEM_UPDATE',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  NOTIFICATION: 'NOTIFICATION',
};

// ============================================================
// 🎯 Event Types (for filtering)
// ============================================================
export const NOTIFICATION_TYPES = {
  CHAT: 'CHAT',
  DEAL: 'DEAL',
  WALLET: 'WALLET',
  ADMIN: 'ADMIN',
  REVIEW: 'REVIEW',
  VERIFICATION: 'VERIFICATION',
  POST: 'POST',
  SYSTEM: 'SYSTEM',
  CANCELLATION: 'CANCELLATION',
  MILESTONE: 'MILESTONE',
  USER: 'USER',
  REPORT: 'REPORT',
  DISPUTE: 'DISPUTE',
};

// ============================================================
// 🎯 Event to Type Mapping
// ============================================================
export const NOTIFICATION_EVENT_TYPES = {
  // ── Chat ──
  [NOTIFICATION_EVENTS.CHAT_MESSAGE]: NOTIFICATION_TYPES.CHAT,
  [NOTIFICATION_EVENTS.CHAT_IMAGE]: NOTIFICATION_TYPES.CHAT,
  [NOTIFICATION_EVENTS.CHAT_PROPOSAL]: NOTIFICATION_TYPES.CHAT,
  [NOTIFICATION_EVENTS.CHAT_PROPOSAL_ACCEPTED]: NOTIFICATION_TYPES.CHAT,
  [NOTIFICATION_EVENTS.CHAT_PROPOSAL_REJECTED]: NOTIFICATION_TYPES.CHAT,
  [NOTIFICATION_EVENTS.CHAT_DEAL_STARTED]: NOTIFICATION_TYPES.CHAT,
  [NOTIFICATION_EVENTS.CHAT_USER_BLOCKED]: NOTIFICATION_TYPES.CHAT,
  [NOTIFICATION_EVENTS.CHAT_USER_UNBLOCKED]: NOTIFICATION_TYPES.CHAT,

  // ── Deal ──
  [NOTIFICATION_EVENTS.DEAL_CREATED]: NOTIFICATION_TYPES.DEAL,
  [NOTIFICATION_EVENTS.DEAL_CONFIRMED]: NOTIFICATION_TYPES.DEAL,
  [NOTIFICATION_EVENTS.DEAL_APPROVED]: NOTIFICATION_TYPES.DEAL,
  [NOTIFICATION_EVENTS.DEAL_REJECTED]: NOTIFICATION_TYPES.DEAL,
  [NOTIFICATION_EVENTS.DEAL_REOPENED]: NOTIFICATION_TYPES.DEAL,
  [NOTIFICATION_EVENTS.DEAL_COMPLETED]: NOTIFICATION_TYPES.DEAL,
  [NOTIFICATION_EVENTS.DEAL_CANCELLED]: NOTIFICATION_TYPES.DEAL,
  [NOTIFICATION_EVENTS.DEAL_EXTENDED]: NOTIFICATION_TYPES.DEAL,
  [NOTIFICATION_EVENTS.DEAL_DEADLINE_PASSED]: NOTIFICATION_TYPES.DEAL,
  [NOTIFICATION_EVENTS.DEADLINE_PASSED]: NOTIFICATION_TYPES.DEAL,
  [NOTIFICATION_EVENTS.DEAL_OVERDUE]: NOTIFICATION_TYPES.DEAL,
  [NOTIFICATION_EVENTS.DISPUTE_OPENED]: NOTIFICATION_TYPES.DISPUTE,
  [NOTIFICATION_EVENTS.OFFER_EXPIRED]: NOTIFICATION_TYPES.DEAL, // ✅ নতুন

  // ── Milestone ──
  [NOTIFICATION_EVENTS.MILESTONE_FUNDED]: NOTIFICATION_TYPES.MILESTONE,
  [NOTIFICATION_EVENTS.MILESTONE_REVIEW]: NOTIFICATION_TYPES.MILESTONE,
  [NOTIFICATION_EVENTS.MILESTONE_RELEASED]: NOTIFICATION_TYPES.MILESTONE,
  [NOTIFICATION_EVENTS.MILESTONE_SUBMITTED]: NOTIFICATION_TYPES.MILESTONE, // ✅ নতুন
  [NOTIFICATION_EVENTS.MILESTONE_REJECTED]: NOTIFICATION_TYPES.MILESTONE, // ✅ নতুন
  [NOTIFICATION_EVENTS.MILESTONE_REFUNDED]: NOTIFICATION_TYPES.MILESTONE, // ✅ নতুন

  // ── Cancellation ──
  [NOTIFICATION_EVENTS.CANCELLATION_REQUEST]: NOTIFICATION_TYPES.CANCELLATION,
  [NOTIFICATION_EVENTS.CANCELLATION_APPROVED]: NOTIFICATION_TYPES.CANCELLATION,
  [NOTIFICATION_EVENTS.CANCELLATION_REJECTED]: NOTIFICATION_TYPES.CANCELLATION,

  // ── Wallet ──
  [NOTIFICATION_EVENTS.DEPOSIT_APPROVED]: NOTIFICATION_TYPES.WALLET,
  [NOTIFICATION_EVENTS.DEPOSIT_REJECTED]: NOTIFICATION_TYPES.WALLET,
  [NOTIFICATION_EVENTS.WITHDRAW_APPROVED]: NOTIFICATION_TYPES.WALLET,
  [NOTIFICATION_EVENTS.WITHDRAW_REJECTED]: NOTIFICATION_TYPES.WALLET,
  [NOTIFICATION_EVENTS.WALLET_CREDITED]: NOTIFICATION_TYPES.WALLET,
  [NOTIFICATION_EVENTS.WALLET_DEBITED]: NOTIFICATION_TYPES.WALLET,
  [NOTIFICATION_EVENTS.PAYMENT_RECEIVED]: NOTIFICATION_TYPES.WALLET,
  [NOTIFICATION_EVENTS.PAYMENT_RELEASED]: NOTIFICATION_TYPES.WALLET,

  // ── Admin ──
  [NOTIFICATION_EVENTS.ADMIN_ANNOUNCEMENT]: NOTIFICATION_TYPES.ADMIN,
  [NOTIFICATION_EVENTS.ADMIN_NOTIFICATION]: NOTIFICATION_TYPES.ADMIN,

  // ── User (Admin) ──
  [NOTIFICATION_EVENTS.USER_VERIFIED]: NOTIFICATION_TYPES.USER,
  [NOTIFICATION_EVENTS.USER_BLOCKED]: NOTIFICATION_TYPES.USER,
  [NOTIFICATION_EVENTS.USER_UNBLOCKED]: NOTIFICATION_TYPES.USER,

  // ── Report (Admin) ──
  [NOTIFICATION_EVENTS.REPORT_RESOLVED]: NOTIFICATION_TYPES.REPORT,
  [NOTIFICATION_EVENTS.REPORT_CANCELLED]: NOTIFICATION_TYPES.REPORT,

  // ── Review ──
  [NOTIFICATION_EVENTS.REVIEW_RECEIVED]: NOTIFICATION_TYPES.REVIEW,
  [NOTIFICATION_EVENTS.REVIEW_REQUESTED]: NOTIFICATION_TYPES.REVIEW,

  // ── Verification ──
  [NOTIFICATION_EVENTS.VERIFY_APPROVED]: NOTIFICATION_TYPES.VERIFICATION,
  [NOTIFICATION_EVENTS.VERIFY_REJECTED]: NOTIFICATION_TYPES.VERIFICATION,

  // ── Post ──
  [NOTIFICATION_EVENTS.POST_APPROVED]: NOTIFICATION_TYPES.POST,
  [NOTIFICATION_EVENTS.POST_REJECTED]: NOTIFICATION_TYPES.POST,

  // ── System ──
  [NOTIFICATION_EVENTS.SYSTEM]: NOTIFICATION_TYPES.SYSTEM,
  [NOTIFICATION_EVENTS.SYSTEM_UPDATE]: NOTIFICATION_TYPES.SYSTEM,
  [NOTIFICATION_EVENTS.SYSTEM_ERROR]: NOTIFICATION_TYPES.SYSTEM,
  [NOTIFICATION_EVENTS.NOTIFICATION]: NOTIFICATION_TYPES.SYSTEM,
};

// ============================================================
// 🎯 Event Priorities
// ============================================================
export const NOTIFICATION_PRIORITIES = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
};

export const NOTIFICATION_EVENT_PRIORITIES = {
  // ── Critical ──
  [NOTIFICATION_EVENTS.SYSTEM_ERROR]: NOTIFICATION_PRIORITIES.CRITICAL,
  [NOTIFICATION_EVENTS.DISPUTE_OPENED]: NOTIFICATION_PRIORITIES.CRITICAL,

  // ── High ──
  [NOTIFICATION_EVENTS.DEPOSIT_APPROVED]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_EVENTS.WITHDRAW_APPROVED]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_EVENTS.DEAL_APPROVED]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_EVENTS.DEAL_REJECTED]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_EVENTS.DEAL_CONFIRMED]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_EVENTS.CANCELLATION_REQUEST]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_EVENTS.CANCELLATION_APPROVED]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_EVENTS.DEADLINE_PASSED]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_EVENTS.ADMIN_ANNOUNCEMENT]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_EVENTS.ADMIN_NOTIFICATION]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_EVENTS.USER_VERIFIED]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_EVENTS.USER_BLOCKED]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_EVENTS.REPORT_RESOLVED]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_EVENTS.DEAL_OVERDUE]: NOTIFICATION_PRIORITIES.HIGH,
  [NOTIFICATION_EVENTS.OFFER_EXPIRED]: NOTIFICATION_PRIORITIES.HIGH, // ✅ নতুন
  [NOTIFICATION_EVENTS.MILESTONE_REJECTED]: NOTIFICATION_PRIORITIES.HIGH, // ✅ নতুন
  [NOTIFICATION_EVENTS.MILESTONE_REFUNDED]: NOTIFICATION_PRIORITIES.HIGH, // ✅ নতুন

  // ── Medium ──
  [NOTIFICATION_EVENTS.CHAT_MESSAGE]: NOTIFICATION_PRIORITIES.MEDIUM,
  [NOTIFICATION_EVENTS.CHAT_IMAGE]: NOTIFICATION_PRIORITIES.MEDIUM,
  [NOTIFICATION_EVENTS.REVIEW_RECEIVED]: NOTIFICATION_PRIORITIES.MEDIUM,
  [NOTIFICATION_EVENTS.NOTIFICATION]: NOTIFICATION_PRIORITIES.MEDIUM,
  [NOTIFICATION_EVENTS.USER_UNBLOCKED]: NOTIFICATION_PRIORITIES.MEDIUM,
  [NOTIFICATION_EVENTS.REPORT_CANCELLED]: NOTIFICATION_PRIORITIES.MEDIUM,
  [NOTIFICATION_EVENTS.MILESTONE_SUBMITTED]: NOTIFICATION_PRIORITIES.MEDIUM, // ✅ নতুন

  // ── Low ──
  [NOTIFICATION_EVENTS.SYSTEM_UPDATE]: NOTIFICATION_PRIORITIES.LOW,
};

// ============================================================
// 🎯 Event Descriptions (for Settings UI)
// ============================================================
export const NOTIFICATION_EVENT_DESCRIPTIONS = {
  // ── Chat ──
  [NOTIFICATION_EVENTS.CHAT_MESSAGE]: 'New chat message received',
  [NOTIFICATION_EVENTS.CHAT_IMAGE]: 'New image received in chat',
  [NOTIFICATION_EVENTS.CHAT_PROPOSAL]: 'New proposal received',
  [NOTIFICATION_EVENTS.CHAT_PROPOSAL_ACCEPTED]: 'Proposal was accepted',
  [NOTIFICATION_EVENTS.CHAT_PROPOSAL_REJECTED]: 'Proposal was rejected',
  [NOTIFICATION_EVENTS.CHAT_DEAL_STARTED]: 'A new deal has started',
  [NOTIFICATION_EVENTS.CHAT_USER_BLOCKED]: 'User was blocked',
  [NOTIFICATION_EVENTS.CHAT_USER_UNBLOCKED]: 'User was unblocked',

  // ── Deal ──
  [NOTIFICATION_EVENTS.DEAL_CREATED]: 'New deal created',
  [NOTIFICATION_EVENTS.DEAL_CONFIRMED]: 'Deal was confirmed',
  [NOTIFICATION_EVENTS.DEAL_APPROVED]: 'Deal was approved',
  [NOTIFICATION_EVENTS.DEAL_REJECTED]: 'Deal was rejected',
  [NOTIFICATION_EVENTS.DEAL_REOPENED]: 'Deal was reopened',
  [NOTIFICATION_EVENTS.DEAL_COMPLETED]: 'Deal completed successfully',
  [NOTIFICATION_EVENTS.DEAL_CANCELLED]: 'Deal was cancelled',
  [NOTIFICATION_EVENTS.DEAL_EXTENDED]: 'Deal deadline was extended',
  [NOTIFICATION_EVENTS.DEAL_DEADLINE_PASSED]: 'Deal deadline has passed',
  [NOTIFICATION_EVENTS.DEADLINE_PASSED]: 'Deal deadline has passed',
  [NOTIFICATION_EVENTS.DEAL_OVERDUE]: 'Deal is overdue (deadline + grace period passed)',
  [NOTIFICATION_EVENTS.DISPUTE_OPENED]: 'A dispute was opened on this deal',
  [NOTIFICATION_EVENTS.OFFER_EXPIRED]: 'A pending offer expired with no response and was auto-cancelled', // ✅ নতুন

  // ── Milestone ──
  [NOTIFICATION_EVENTS.MILESTONE_FUNDED]: 'Milestone was funded',
  [NOTIFICATION_EVENTS.MILESTONE_REVIEW]: 'Milestone review requested',
  [NOTIFICATION_EVENTS.MILESTONE_RELEASED]: 'Milestone payment released',
  [NOTIFICATION_EVENTS.MILESTONE_SUBMITTED]: 'Seller submitted work for a funded milestone', // ✅ নতুন
  [NOTIFICATION_EVENTS.MILESTONE_REJECTED]: 'Buyer rejected submitted work — seller can resubmit', // ✅ নতুন
  [NOTIFICATION_EVENTS.MILESTONE_REFUNDED]: 'Milestone funds were auto-refunded (no submission in time)', // ✅ নতুন

  // ── Cancellation ──
  [NOTIFICATION_EVENTS.CANCELLATION_REQUEST]: 'Deal cancellation requested',
  [NOTIFICATION_EVENTS.CANCELLATION_APPROVED]: 'Deal cancellation approved',
  [NOTIFICATION_EVENTS.CANCELLATION_REJECTED]: 'Deal cancellation rejected',

  // ── Wallet ──
  [NOTIFICATION_EVENTS.DEPOSIT_APPROVED]: 'Deposit was approved',
  [NOTIFICATION_EVENTS.DEPOSIT_REJECTED]: 'Deposit was rejected',
  [NOTIFICATION_EVENTS.WITHDRAW_APPROVED]: 'Withdrawal was approved',
  [NOTIFICATION_EVENTS.WITHDRAW_REJECTED]: 'Withdrawal was rejected',
  [NOTIFICATION_EVENTS.WALLET_CREDITED]: 'Money added to wallet',
  [NOTIFICATION_EVENTS.WALLET_DEBITED]: 'Money deducted from wallet',
  [NOTIFICATION_EVENTS.PAYMENT_RECEIVED]: 'Payment received',
  [NOTIFICATION_EVENTS.PAYMENT_RELEASED]: 'Payment released',

  // ── Admin ──
  [NOTIFICATION_EVENTS.ADMIN_ANNOUNCEMENT]: 'Admin announcement',
  [NOTIFICATION_EVENTS.ADMIN_NOTIFICATION]: 'Admin notification',

  // ── User (Admin) ──
  [NOTIFICATION_EVENTS.USER_VERIFIED]: 'User account was verified',
  [NOTIFICATION_EVENTS.USER_BLOCKED]: 'User account was blocked',
  [NOTIFICATION_EVENTS.USER_UNBLOCKED]: 'User account was unblocked',

  // ── Report (Admin) ──
  [NOTIFICATION_EVENTS.REPORT_RESOLVED]: 'Report was resolved',
  [NOTIFICATION_EVENTS.REPORT_CANCELLED]: 'Report was cancelled',

  // ── Review ──
  [NOTIFICATION_EVENTS.REVIEW_RECEIVED]: 'New review received',
  [NOTIFICATION_EVENTS.REVIEW_REQUESTED]: 'Review requested',

  // ── Verification ──
  [NOTIFICATION_EVENTS.VERIFY_APPROVED]: 'Verification approved',
  [NOTIFICATION_EVENTS.VERIFY_REJECTED]: 'Verification rejected',

  // ── Post ──
  [NOTIFICATION_EVENTS.POST_APPROVED]: 'Post was approved',
  [NOTIFICATION_EVENTS.POST_REJECTED]: 'Post was rejected',

  // ── System ──
  [NOTIFICATION_EVENTS.SYSTEM]: 'System notification',
  [NOTIFICATION_EVENTS.SYSTEM_UPDATE]: 'System update available',
  [NOTIFICATION_EVENTS.SYSTEM_ERROR]: 'System error occurred',
  [NOTIFICATION_EVENTS.NOTIFICATION]: 'General notification',
};

// ============================================================
// 🎯 Helper Functions
// ============================================================

/**
 * Get event type (category)
 */
export const getEventType = (event) => {
  return NOTIFICATION_EVENT_TYPES[event] || NOTIFICATION_TYPES.SYSTEM;
};

/**
 * Get event priority
 */
export const getEventPriority = (event) => {
  return NOTIFICATION_EVENT_PRIORITIES[event] || NOTIFICATION_PRIORITIES.MEDIUM;
};

/**
 * Get event description
 */
export const getEventDescription = (event) => {
  return NOTIFICATION_EVENT_DESCRIPTIONS[event] || event;
};

/**
 * Check if event is high priority
 */
export const isHighPriority = (event) => {
  const priority = getEventPriority(event);
  return priority === NOTIFICATION_PRIORITIES.CRITICAL || 
         priority === NOTIFICATION_PRIORITIES.HIGH;
};

/**
 * Check if event exists
 */
export const isValidEvent = (event) => {
  return Object.values(NOTIFICATION_EVENTS).includes(event);
};

// ============================================================
// 🎯 Default Export
// ============================================================
export default {
  NOTIFICATION_EVENTS,
  NOTIFICATION_TYPES,
  NOTIFICATION_EVENT_TYPES,
  NOTIFICATION_PRIORITIES,
  NOTIFICATION_EVENT_PRIORITIES,
  NOTIFICATION_EVENT_DESCRIPTIONS,
  getEventType,
  getEventPriority,
  getEventDescription,
  isHighPriority,
  isValidEvent,
};